### ISSUE TITLE
TypeError with unicode string in Geom.label

### ISSUE THREAD

**Issue by protogeezer** [dcjones/Gadfly.jl#710]
example:
str1 = @sprintf("equation: %6.3f⋅X + %6.3f",x[2],x[1])
df_label1 = DataFrame(x=2,y=96,str=str1);
and in the plot command:
...
layer(df_label1,x="x",y="y",label="str",Geom.label())
---
with the dot operator (before the X) a unicode string is created, resulting in the following error:

ERROR: TypeError: setfield!: expected Union{DataArrays.PooledDataArray{T,R<:Integer,N},Void}, got Array{UTF8String,1}
 in concat at /Users/sjbespa/.julia/v0.4/Gadfly/src/aesthetics.jl:263
 in render_prepare at /Users/sjbespa/.julia/v0.4/Gadfly/src/Gadfly.jl:674
...

If there was a way to create a label without the DataFrame, simple and straightforward.

**Comment by tbreloff** [comment]
Can you provide the full code, as well as a better description of what you want to do? Are you trying to make one annotation within the plot, or something else?

**Comment by protogeezer** [comment]
Sure. When the error happened, I was attempting to put an annotation consisting of an equation on a single plot. In my opinion, for cases similar to this one, the use of the data frame seems gratuitous.

Although this is a separate problem, the browser based preview appears to lose track of the baseline after the exponent in the other label - although this could be due to the fontconfig, etc, not being installed properly. Also, when the preview is magnified the exponent ends up being about 20x too tall. I mention it here because I don't have time to do any more analysis. I attached a screen snap.

![2muchofagoodthing](https://cloud.githubusercontent.com/assets/5422230/10198545/bebfbc22-6759-11e5-8eec-3cf899b3803e.png)

Here is a simplified version of the code:
==============================
using Gadfly, DataFrames
x = [-2.664, 53.570]
sl = 2*randn(2_000);
inter = 10*randn(2_000)+50;
df_scatter = DataFrame(slope=sl, intercept=inter);
#TypeError with this label
str1 = @sprintf("equation: %6.3f⋅X + %6.3f",x[2],x[1])
#No error with ascii version of label
#str1 = @sprintf("equation: %6.3fX + %6.3f",x[2],x[1])
df_label1 = DataFrame(x=2,y=96,str=str1);
df_label2 = DataFrame(x=2,y=91,str="constraint: R<sup>2</sup> > 0.5");
plot( layer(df_scatter,y="intercept",x="slope",Geom.histogram2d),
			layer(x=[-10,10],y=[85,25],Geom.line),
			layer(df_label1,x="x",y="y",label="str",Geom.label()),
			layer(df_label2,x="x",y="y",label="str",Geom.label()))

**Comment by tbreloff** [comment]
I threw your example in a IJulia notebook:  

```
srand(1234)
x = [-2.664, 53.570]
sl = 2randn(2_000)
inter = 10randn(2_000)+50
str1_err = @sprintf("equation: %6.3f⋅X + %6.3f",x[2],x[1])
str1_ok = @sprintf("equation: %6.3fX + %6.3f",x[2],x[1])
str2_err = "constraint: R² > 0.5";
str2_ok = "constraint: R2 > 0.5";
```

I confirm that there's an error with the "_err" strings... with the "_ok" strings I get the expected result with:
```
using Gadfly, DataFrames
df_scatter = DataFrame(slope=sl, intercept=inter);
df_label1 = DataFrame(x=1,y=94,str=str1_ok);
df_label2 = DataFrame(x=1,y=88,str=str2_ok);
plot( layer(df_scatter,y="intercept",x="slope",Geom.histogram2d),
        layer(x=[-10,10],y=[85,25],Geom.line),
        layer(df_label1,x="x",y="y",label="str",Geom.label()),
        layer(df_label2,x="x",y="y",label="str",Geom.label()))
```

However, this type of annoyance is one of the main reasons I started Plots.jl.  Here's essentially the same plot through Plots (most of the params are just so I could match the output closely):
```
using Plots
heatmap(sl, inter, nbins=150, 
        size=(550,350), leg=false,
        xlab="slope",ylab="intercept",
        annotation=[(1,94,str1_err), (1,88,str2_err)])
plot!([-10,10],[85,25], c=:cyan)
```
![tmp](https://cloud.githubusercontent.com/assets/933338/10209231/e0e05cc2-679e-11e5-8d1c-9ac9601da6e8.png)

Under the hood, I'm building Gadfly commands, and the text annotations are generated partially with [this code](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/gadfly.jl#L362-L367)

**Comment by dcjones** [comment]
Fixed in master now, thanks for reporting. 

Btw, you never have to use data frames in gadfly, it only exists as a slight convenience if your data is already in a data frame. E.g. this is an equivalent way to draw your plot
```julia
plot(layer(x=sl, y=inter, Geom.histogram2d),
     layer(x=[-10,10], y=[85,25], Geom.line),
     layer(x=[2, 2], y=[96, 91],
           label=[@sprintf("equation: %6.3f⋅X + %6.3f",x[2],x[1]),
                  "constraint: R2 > 0.5"], Geom.label))
```

**Comment by tbreloff** [comment]
Side question... what's the difference between a Guide.annotation and a
Geom.label?  Is one more performant? Do they have different uses?

**Comment by dcjones** [comment]
`Guide.annotation` is kind of an escape hatch that let's you draw anything on the plot. `Geom.label` is specifically for text labels, and does layout optimization, moving and hiding labels to avoid overlaps.

**Comment by protogeezer** [comment]
Thanks. A question before I get too far along. I’m still getting literally tens of thousands of 

WARNING: Union(args...) is deprecated, use Union{args...} instead.

messages from a few places in Gadfly/Compose. Have I mangled my installation some how, are those fixes in the pipeline, or do those need to be reported? Table.jl:352 for example.

Stephen

**Comment by dcjones** [comment]
Should be fixed after updating.

**Comment by protogeezer** [comment]
Excellent! But maybe this is something to look into?

WARNING: eval from module Compose to Gadfly:    
Expr(:import, :Patchwork)::Any
  ** incremental compilation may be broken for this module **
